export default {
  feed: '/',
  search: '/search',
  newPost: '/new',
  repost: '/repost',
  postHash: '/post/:hash',
  post: '/post',
  profile: '/profile',
  notification: '/notification',
  register: '/register',
  login: '/login',
  passwordRecovery: '/password-recovery',
  source: '/source',
  sourceAddress: '/source/:address',
  tag: '/tag',
  tagTagName: '/tag/:tag',
};
